### ISSUE TITLE
Permit verification of typed methods without setup

### ISSUE THREAD

**Issue by laingsimon** [laingsimon/Dapper.MoqTests#10]
Currently you have to verify a method call using `object` as the type parameter if no setup is defined.

It should be possible to intercept and verify the following, by modifying the type parameter to `object` if no setup can be found.

```
connection.QueryAsync<Car>()
```

**Comment by ghost** [comment]
Attempting to modify the verification so it is typed to object rather than the expected type fails; as the expression becomes invalid.

```
System.ArgumentException: 'Expression of type 'System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[System.Object]]' cannot be used for return type 'System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[Dapper.MoqTests.Samples.Car]]''
```

It could with a wholesale rewrite of the expression?

**Comment by laingsimon** [comment]
The current (attempted) process rewrites the method call so it yields IEnumerable<object>. This works fine, but cannot be included in the required Task<T> as it's not been rewritten at the same time.

**Comment by laingsimon** [comment]
It should be possible to modify the entire expression as this would be for verification only, it won't actually execute anything

**Comment by laingsimon** [comment]
The complication with the approach of modifying the verify expression is the same needs to be done for the setup, which in itself presents issues. The setup method returns a fluent interface typed to that.of the return parameter. This would be Object (for example) instead of Car or some other more correctly defined type.

As such a setup can lose information and 'capability' by this approach. We'll need to find another way...

**Comment by ghost** [comment]
TypeDeserializerCache.GetReader maybe a place where we can work out the actual type for the Dapper command?

**Comment by ghost** [comment]
See https://raw.githubusercontent.com/StackExchange/Dapper/master/Dapper/SqlMapper.cs

**Comment by ghost** [comment]
Some success has been made by interrogating the CommandCache in the SqlMapper. It's not.fool proof so may not be a reliable or appropriate solution
