### ISSUE TITLE
Querying data using CommandDefinitions

### ISSUE THREAD

**Issue by roly445** [laingsimon/Dapper.MoqTests#27]
I have been unit testing dapper with your library for a while and its really nice and easy to use.

I have recently started to pass cancellation tokens around my code and I am now passing them in to my dapper calls.  Unfortunately this requires use of a CommandDefinition and not parameters into the query directly.

Is this something you would be able to have a look into adding your library?

**Comment by ghost** [comment]
That's a good idea, i am sure it could be added in, but would require a bit of investigation.

**Comment by ghost** [comment]
Hi @roly445 are you able to provide a sample that can be included in the samples project for how you would like to use this overload?

It can then be used as a test - in a sense - to develop against.

**Comment by laingsimon** [comment]
The changes work with dotnet Core and with a debug .net framework build. But fails on a release build.

The failure is due to code optimization by the compiler which removes certain methods from the call stack. Investigating solutions after the refactor.

**Comment by laingsimon** [comment]
A solution that appears to build, in release (.net framework) doesn't work when built via CI. Requires further investigation.

**Comment by laingsimon** [comment]
@roly445 would you want/need this for a dotnet Core version of the package or would it be for .net framework?

I'm looking into ways to make it universally compatible, but it is proving to be a challenge at the moment
