### ISSUE TITLE
Include Asp.net Core 3.1 compatibillity

### ISSUE THREAD

**Issue by fabrizziocht** [laingsimon/Dapper.MoqTests#28]
Is it posible to include asp.net core 3.1 compatibillity? It only works with .NetFramework 4.6+

**Comment by ghost** [comment]
Sorry for the delay, i'm currently looking at porting the library across to dotnet Core 3.1, but maintaining support for .net framework also wherever possible.

**Comment by laingsimon** [comment]
New dotnet framework package deployed - v1.6.24

**Comment by laingsimon** [comment]
Initial dotnet core package deployed as https://www.nuget.org/packages/Dapper.MoqTests.Core/

**Comment by laingsimon** [comment]
@fabrizziocht would you please be able to:

1. Check that this package works for you - Dapper.MoqTests.Core - v1.6.29
2. If this package works for you, would you be able to unlist Dapper.MoqTestsCore to remove any confusion about the which package is 'official'

Finally, thanks for the suggestion and for doing this yourself, if you have other suggestions, please let me know or make a pull request so they can be incorporated into the main code/package.

Sorry for the delay.
