### ISSUE TITLE
Unable to detect the identity for the command, it could have been one of 1 possible options"

### ISSUE THREAD

**Issue by mhectorgato** [laingsimon/Dapper.MoqTests#29]
◢ | $exception | {"Unable to detect the identity for the command, it could have been one of 1 possible options.\n\ncommand: 'DELETE admin.dbo.BillingEntityAccess WHERE UserID = @UserID AND BillingEntityID IN (@Locations1)'\nParameters: `UserId = f68ee905-86ab-4ddd-ac51-1dbbd4e9d931, Locations1 = 123`\nCommandType: Text\n\nTo be able to Verify the Dapper call accurately the Command and Parameters (and return type) must be unique for every invocation of a Dapper method."} | System.InvalidOperationException

**Comment by ghost** [comment]
Hi @mhectorgato is this a duplicate of #30?

**Comment by laingsimon** [comment]
Closing as a duplicate, will reopen if this isn't the case
