### ISSUE TITLE
Please add support for System.Threading.Tasks.Task`1[T] ExecuteScalarAsync[T](System.Data.IDbConnection, Dapper.CommandDefinition)

### ISSUE THREAD

**Issue by VictorioBerra** [laingsimon/Dapper.MoqTests#36]
**Is your feature request related to a problem? Please describe.**
System.NotSupportedException : Could not find method map for System.Threading.Tasks.Task`1[T] ExecuteScalarAsync[T](System.Data.IDbConnection, Dapper.CommandDefinition)
    Found 0 method/s in DapperMethodMap that match System.Threading.Tasks.Task`1[T] ExecuteScalarAsync[T](System.Data.IDbConnection, Dapper.CommandDefinition) (compareParameters: False)
    Found 0 overload/s that match
    Found 0 method/s in MockDatabase that match System.Threading.Tasks.Task`1[T] ExecuteScalarAsync[T](System.Data.IDbConnection, Dapper.CommandDefinition) (compareParameters: True)
    Found 0 overload/s that match

**Comment by laingsimon** [comment]
Hi @VictorioBerra can you please include the steps to reproduce this issue, such as the call to Dapper?

Also can you please confirm if you have set the setting `PreferCommandDefinitions` to `true`

**Comment by VictorioBerra** [comment]
I will try PreferCommandDefinitions to true and get back to you, I am also in the middle of a refactor to .NET 5 so it might be a couple days. Thank you for your quick response!

**Comment by VictorioBerra** [comment]
Closing for now as I don't have time to get my code in shape enough to inject the test connection. If I ever circle back to this ill re-open.
