### ISSUE TITLE
Support for .NET 5.0

### ISSUE THREAD

**Issue by imad-mn** [laingsimon/Dapper.MoqTests#38]
Simon @laingsimon,

Some people started using .NET 5.0 but when installed latest version 1.7.13 it shows a warning in Visual Studio.
Can you please add support for .NET 5.0 🙏  ?

**Comment by laingsimon** [comment]
Hi, I can take a look at this and thanks for letting me known can you please advise on what the warnings are and the setup that causes these warnings to show

**Comment by imad-mn** [comment]
Sure, this is the package console text:
`Package 'Dapper.MoqTests 1.7.13' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.`

**Comment by imad-mn** [comment]
Should I use **Dapper.MoqTests.Core** instead ?
I had no warnings with that one :-)

**Comment by imad-mn** [comment]
Closing this issue since .NET 5.0 IS .Net Core, so I should Use Dapper.MoqTests.Core

**Comment by laingsimon** [comment]
Yes, you're right, the dotnet core package should be used instead. Let me know if you have any other issues
