### ISSUE TITLE
Using QueryAsync/ReturnsAsync and comparing expected result.

### ISSUE THREAD

**Issue by imad-mn** [laingsimon/Dapper.MoqTests#39]
Hello again Simon @laingsimon,

Can you guide me through why the response is a list with 1 element and it's a totally different pointer (in memory) than the expected result that I set it up.  

```
        public  async Task GetAll_successfully()
        {
            // Arrange
            var expected = new List<WarehouseSimple>();
            dbConnectionMock.Setup(x => x.QueryAsync<WarehouseSimple>(
                                It.IsAny<string>(), null, It.IsAny<IDbTransaction>(), null, null))
                            .ReturnsAsync(expected);
            // Act
            var result = await repository.GetAll();

            // Assert
            Assert.Equal(expected, result);
        }
```

Am I not following the normal use of this library ?

**Comment by laingsimon** [comment]
Hi @imad-mn let me take a look and come back to you.

**Comment by laingsimon** [comment]
In the meantime, is your scenario similar to any of the samples in the project?

https://github.com/laingsimon/Dapper.MoqTests/blob/master/Dapper.MoqTests.Samples/Samples.cs

**Comment by imad-mn** [comment]
I read the sample class many times, looks like you normally **Verify** that the SQL query is the one being executed.
Is that the usage of this library?
My closest sample is _SetupOnly()_ method

**Comment by laingsimon** [comment]
Yes the usage of the library is more about verifying that calls are made rather than what those calls return.

Your use case is one I've not explored yet, so I'm keen to see what happens in this case. It is something that in theory could work, but I'll need to confirm that hypothesis.

What is it you're trying to achieve?

**Comment by imad-mn** [comment]
I changed my code to use "Verify". I just want to unit test my repository in any way.
Now, I'm getting this error which I could not get ride of:
```
System.InvalidOperationException : Unable to detect the identity for the command, it could have been one of 3 possible options.
To be able to Verify the Dapper call accurately the Command and Parameters (and return type) must be unique for every invocation of a Dapper method.
```
This is when doing _ExecuteAsync()_, Any idea?

NOTE: If I run this test alone, it runs correctly, but it fails when running it with others.

**Comment by imad-mn** [comment]
**Stack Trace:**
   at Dapper.MoqTests.DapperCacheInfo.GetIdentity(MockDbCommand mockDbCommand, IIdentityComparer identityComparer)
   at Dapper.MoqTests.MockDbCommand.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Dapper.MoqTests.MockDbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646

**Comment by imad-mn** [comment]
If I put` Settings.Default.ResetDapperCachePerCommand = true;` before calling my repository, I still got the same error and stack trace.

**Comment by imad-mn** [comment]
I put `Settings.Default.ResetDapperCachePerCommand = true; `at the test class constructor and worked well !

**Comment by laingsimon** [comment]
I'm glad that helps and if you're using mstest or xunit you'll need this in the constructor of your test class.

I'll have a look at the viability of using the library to return results under a (different) feature request - simply to remove confusion.
